### ISSUE TITLE
Error on calling the PREDICT function

### ISSUE THREAD

**Issue by Navedya06** [Snowflake-Labs/sfguide-getting-started-with-document-ai#3]
Hi @iamontheinet , @sfc-gh-mstellwall,

I am encountering an error when calling the PREDICT function
![image](https://github.com/Snowflake-Labs/sfguide-getting-started-with-document-ai/assets/68197201/82e5b603-0357-429a-9b1e-4d958be0a1d9)

I have granted the role access to stage, and performed the training with the same role as well....

How can I debug this?

**Comment by sfc-gh-mstellwall** [comment]
Hi,

One thing to check is if  your published model have build number 1, so in the details of the DOC_AI_QS_CO_BRANDING build you can see under Extracting Query what build number you have:
<img width="823" alt="image" src="https://github.com/Snowflake-Labs/sfguide-getting-started-with-document-ai/assets/66662692/ced81616-b16e-420c-9f0e-32d877cb6efc">
